---

  # [en_US] Time intervals configuration
  time_intervals:
    # [en_US] Time interval for check if there are available heroes to work
    # Default value (in minutes): 10
    send_heroes_for_work: 11
    
    # [en_US] Time interval to update heroes position in the map,
    # Default value (in minutes): 3
    refresh_heroes_positions: 3
    
    # [en_US] Time interval to check for new maps
    # Default value (in minutes): 3
    check_for_new_map_button: 3
    
    # [en_US] Time interval to check for login request
    # Default value (in minutes): 3
    check_for_login: 5

    # [en_US] Time interval between moviments
    # Default value (in seconds): 1
    interval_between_moviments: 1

    # [en_US] Mouse last movement time limit before F5 (Solve stuck situations Ex: screen w/o buttons)
    # Default value (in minutes): 8
    check_for_game_crash: 8 #min

  # [en_US] How confident the bot needs to be to click the buttons (values from 0 to 1. 0 is the minimum value, 1 is the maximum value)
  threshold:
    # [en_US]
    # Default value: 0.7
    default: 0.8

    # [en_US]
    # Default value: 0.8
    commom: 0.8

    # [en_US]
    # Default value: 0.8
    select_wallet_buttons: 0.8

    # [en_US]
    # Default value: 0.9
    go_to_work_btn: 0.9

    # [en_US]
    # Default value: 0.9
    green_bar: 0.9

  # [en_US]
  # Default value: 60
  scroll_size: 60

# [en_US]
  # Default value: 3
  scroll_attemps: 3

  # [en_US]
  # Default value: true
  use_click_and_drag_instead_of_scroll: true

  # [en_US]
  # Default value: 200
  click_and_drag_amount: 200

  # [en_US]
  # Default value: green
  # Available options:
  # all   = select all heroes (regardless of the stamina bar)
  # green = select the heroes with green stamina bar (half or full)
  # full  = select only the heroes with full stamina bar
  select_heroes_mode: "green"

  # [en_US] Option for save logs to a file (logs.txt)
  # Default value: False
  # Available options: False or True
  save_log_to_file: False
